function [fig,P1,P2] = exportBarChart(T,varargin)
%EXPORTBARCHART Export bar chart for Figure 4 by-area comparisons
%
%   fig = exportBarChart(T);
%   fig = exportBarChart(T,'Name',value,...);
%   [fig,P1,P2] = ... 
%
% Inputs
%   T - Data table from `IntensityStatsTable.xlsx`
%   varargin - (Optional) 'Name',value pairs for `bar` object
%
% Output
%   fig - Figure handle
%   [P1,P2] - Return first and second properties tables also.
%
% See also: main.m

% First properties table
Group = ["SHAM"; "ADS"; "RS"];
Color = [0 0 0; 0 0 1; 1 0 0];
Offset = [-0.5; 0; 0.5];
P1 = table(Group,Color,Offset);

% Second properties table
ID = ["LH S1"; "LH RFA"; "RH S1"; "RH RFA"];
XTick = [1;3;5;7];
P2 = table(ID,XTick);

fig = figure(...
    'Name','Average pixel intensity By Area',...
    'Color','w',...
    'PaperOrientation','portrait',...
    'Units','Normalized',...
    'PaperUnits','inches',...
    'PaperSize',[8.5 11],...
    'Position',[0.3 0.3 0.29 0.38]);

ax = axes(fig,'XColor','k','YColor','k','NextPlot','add',...
    'LineWidth',1.5,'FontName','Arial','FontSize',16,...
    'XTick',XTick,'XLim',[0 8],...
    'XTickLabels',ID);
ylabel(ax,'Mean Pixel Intensity',...
    'FontName','Arial','Color','k','FontSize',16);

% Group data
T.ID = strcat(T.Hemisphere," ",T.Area);
[G,TID] = findgroups(T(:,{'ID','Group'}));
TID.Mean = splitapply(@nanmean,T.Value,G);
TID.SD = splitapply(@nanstd,T.Value,G);


for ii = 1:size(P1,1)
    t = TID(TID.Group==P1.Group(ii),:);
    t = outerjoin(t,P2,'Type','left',...
        'LeftVariables',{'ID','Group','Mean','SD'},...
        'RightVariables',{'XTick'},...
        'Keys',{'ID'});
    t.X = t.XTick + P1.Offset(ii);
    bar(ax,t.X,t.Mean,...
        'EdgeColor','none',...
        'FaceColor',P1.Color(ii,:),...
        'DisplayName',P1.Group(ii),...
        'Tag',P1.Group(ii),'BarWidth',0.20);
    h = errorbar(t.X,t.Mean,-t.SD*0.5,t.SD*0.5,...
        'Parent',ax,...
        'LineWidth',1.5,'Color','m','LineStyle','none',...
        'DisplayName','1 STD');
    h.Annotation.LegendInformation.IconDisplayStyle = 'off';
end
h.Annotation.LegendInformation.IconDisplayStyle = 'on';
legend(ax,'FontName','Arial','TextColor','black','EdgeColor','none',...
    'FontSize',13,'FontWeight','bold');
end